class PetDetailDataModel{
  final String petName;
  final String petImage;
  final String petType;
  final String distanceFromPet;
  final String petBreed;
  final String petOrganization;
  final String petOrganizationAddress;
  final String petOrganizationImage;
  final String petDescription;
  final String petGender;
  final String petAge;
  final String petSize;
  final String petAdoptInfo;
  final String petDescription2;
  final String petAdoptInfo2;

  PetDetailDataModel({
    required this.petName,
    required this.petImage,
    required this.petType,
    required this.distanceFromPet,
    required this.petBreed,
    required this.petOrganization,
    required this.petDescription,
    required this.petOrganizationAddress,
    required this.petOrganizationImage,
    required this.petAdoptInfo,
    required this.petAge,
    required this.petGender,
    required this.petSize,
    required this.petDescription2,
    required this.petAdoptInfo2,
  });

  PetDetailDataModel copyWith({
    String? petName,
    String? petImage,
    String? petType,
    String? distanceFromPet,
    String? petBreed,
    String? petOrganizationAddress,
    String? petOrganization,
    String? petOrganizationImage,
    String? petDescription,
    String? petAdoptInfo,
    String? petAdoptInfo2,
    String? petDescription2,
    String? petAge,
    String? petSize,
    String? petGender,
  }){
    return PetDetailDataModel(
      petName: petName?? this.petName, 
      petImage: petImage?? this.petImage, 
      petType: petType?? this.petType,
      distanceFromPet: distanceFromPet?? this.distanceFromPet,
      petBreed: petBreed?? this.petBreed,
      petDescription: petDescription?? this.petDescription,
      petOrganization: petOrganization?? this.petOrganization,
      petOrganizationAddress: petOrganizationAddress?? this.petOrganizationAddress,
      petOrganizationImage: petOrganizationImage?? this.petOrganizationImage,
      petAdoptInfo2: petAdoptInfo2?? this.petAdoptInfo2,
      petAdoptInfo: petAdoptInfo?? this.petAdoptInfo,
      petAge: petAge?? this.petAge,
      petGender: petGender?? this.petGender,
      petDescription2: petDescription2?? this.petDescription2,
      petSize: petSize?? this.petSize,

    );
  }
  
  Map<String, dynamic> toJson() => {
    'petName': petName,
    'petImage': petImage,
    'petType': petType,
    'distanceFromPet': distanceFromPet,
    'petBreed': petBreed,
    'petDescription':petDescription,
    'petOrganization': petOrganization,
    'petOrganizationAddress': petOrganizationAddress,
    'petOrganizationImage':petOrganizationImage,
    'petAge': petAge,
    'petGender': petGender,
    'petSize': petSize,
    'petAdoptInfo': petAdoptInfo,
    'petAdoptInfo2': petAdoptInfo2,
    'petDescription2': petDescription2,
  };

  factory PetDetailDataModel.fromJson(Map<String, dynamic>json) => PetDetailDataModel(
    petName: json['petName'], 
    petImage: json['petImage'], 
    petType: json['petType'],
    distanceFromPet: json['distanceFromPet'], 
    petBreed: json['petBreed'],
    petDescription: json['petDescription'],
    petOrganization: json['petOrganization'],
    petOrganizationAddress: json['petOrganizationAddress'],
    petOrganizationImage: json['petOrganizationImage'],
    petAdoptInfo: json['petAdpotInfo'],
    petAdoptInfo2: json['petAdoptInfo'],
    petAge: json['petAge'],
    petDescription2: json['petDescription2'],
    petGender: json['petGender'], 
    petSize: json['petSize'],
  );

  static List<PetDetailDataModel> getPetsByOwner(String ownerName){
    return petDetailList.where((element) => element.petOrganization == ownerName).toList();
  }


  static List<PetDetailDataModel> petDetailList = [
    //cat
    PetDetailDataModel(
      petName: 'Mochi', 
      petImage: 'assets/image/mochi_cat.png', 
      petType: 'Cats', 
      distanceFromPet: '1.2km', 
      petBreed: 'Abyssinian', 
      petOrganization: 'Happy Tails Animal Rescue', 
      petDescription: 'Mochi is a stunning Abyssinian cat with a warm, golden coat that shimmers in the sunlight. This playful and curious feline is just 2 years old, making her the perfect blend of youthful energy and feline charm.', 
      petDescription2: 'Mochi is not just a cat; she\'s a bundle of joy waiting to bring happiness into your home. With her affectionate nature, she enjoys cuddling up on lazy afternoons and is always ready to engage in interactive play. Mochi loves to explore her surroundings and has a special fondness for climbling and perching on high spots to observe the world around her.', 
      petOrganizationAddress: '123 Paws Street. NYC, NY 10001', 
      petOrganizationImage: '',
      petAdoptInfo: 'Mochi is seeking a loving home where she can be the center of attention. An adopter who appreciates her playful antics and can provide a stimulating environment will be the perfect match for this charming Abyssinian. Whether it\'s chasing toys or basking in the sun. Mochi is ready to be your new furry companion.', 
      petAdoptInfo2: 'To inquire about adopting Mochi, please contact the Happy Tails Animal Rescue at (555) 123-4567. The adoption process includes a meet-and-greet to ensure a perfect fit. Mochi is spayed, up-to-date on vaccinations, and comes with a clean bill of health.',
      petAge: 'Adult', 
      petGender: 'Male', 
      petSize: 'Medium', 
    ),

    PetDetailDataModel(
      petName: 'Casper', 
      petImage: 'assets/image/casper_cat.png', 
      petType: 'Cats', 
      distanceFromPet: '1.2km', 
      petBreed: 'Manx', 
      petOrganization: 'Feline Friends Rescue', 
      petDescription: 'Casper is a lovable Manx cat. This gentle cat is known for his calm demeanor and loves lounging in cozy spots.', 
      petDescription2: 'Casper enjoys a peaceful environment and gentle petting sessions. Though a bit shy initially, he warms up quickly and shows affection to those he trusts. Casper is a true lap cat, perfect for a quiet household.', 
      petOrganizationAddress: '753 Andrea Street, Ohio, OH 43029', 
      petOrganizationImage: '',
      petAdoptInfo: 'Casper would thrive in a home that offers stability and gentle companionship. He\'s looking for a loving family to share his calm and affectionate nature with.', 
      petAdoptInfo2: 'To adopt Casper, contact Feline Friends Rescue at (555) 654-3210. He is neutered, vaccinated, and in excellent health.',
      petAge: 'Young', 
      petGender: 'Male', 
      petSize: 'Medium', 
    ),

    PetDetailDataModel(
      petName: 'Willow', 
      petImage: 'assets/image/willow_cat.png', 
      petType: 'Cats', 
      distanceFromPet: '1.5km', 
      petBreed: 'Manx', 
      petOrganization: 'Feline Friends Rescue', 
      petDescription: 'Willow is a lovable Manx cat. This gentle cat is known for his calm demeanor and loves lounging in cozy spots.', 
      petDescription2: 'Willow enjoys a peaceful environment and gentle petting sessions. Though a bit shy initially, he warms up quickly and shows affection to those he trusts. Willow is a true lap cat, perfect for a quiet household.', 
      petOrganizationAddress: '753 Andrea Street, Ohio, OH 43029', 
      petOrganizationImage: '',
      petAdoptInfo: 'Willow would thrive in a home that offers stability and gentle companionship. He\'s looking for a loving family to share his calm and affectionate nature with.', 
      petAdoptInfo2: 'To adopt Willow, contact Feline Friends Rescue at (555) 654-3210. He is neutered, vaccinated, and in excellent health.',
      petAge: 'Adult', 
      petGender: 'Male', 
      petSize: 'Medium', 
    ),

    PetDetailDataModel(
      petName: 'Bella', 
      petImage: 'assets/image/bella_cat.jpg', 
      petType: 'Cats', 
      distanceFromPet: '1.6km', 
      petBreed: 'Persian', 
      petOrganization: 'FurEver Friends', 
      petDescription: 'Bella is a stunning Persian with a luxurious, fluffy coat and big, expressive eyes. She\'s known for her calm, loving personality and adores attention.', 
      petDescription2: 'Bella loves gentle petting and being groomed. She is a true lap cat who prefers cozy spaces and enjoys the quiet company of her favorite humans.', 
      petOrganizationAddress: '789 Persian Alley, Orlando, FL 32801', 
      petOrganizationImage: '',
      petAdoptInfo: 'Bella is looking for a loving home where she can be pampered. She\'ll do best with someone who enjoys her calm, easygoing nature and can give her the care her coat requires.', 
      petAdoptInfo2: 'Reach out to FurEver Friends at (555) 101-2020 to inquire about adopting Bella. She is spayed, vaccinated, and in great health.',
      petAge: 'Senior', 
      petGender: 'Female', 
      petSize: 'Medium', 
    ),

  PetDetailDataModel(
    petName: 'Milo',
    petImage: 'assets/image/milo_cat.jpg',
    petType: 'Cats',
    distanceFromPet: '2.2km',
    petBreed: 'Bengal',
    petOrganization: 'Happy Tails Animal Rescue',
    petDescription: 'Milo is an energetic Bengal with striking, leopard-like spots and a bold, adventurous spirit. Known for his high energy, Milo thrives in an active environment.',
    petDescription2: 'Milo enjoys exploring, climbing, and playing with toys. He\'s very interactive and enjoys attention, especially from people who can match his playful energy.',
    petOrganizationAddress: '123 Paws Street. NYC, NY 10001',
    petOrganizationImage: '',
    petAdoptInfo: 'Milo needs a home where he can be active and mentally stimulated. He\'s perfect for an adopter who understands his energetic personality and can provide a stimulating environment.',
    petAdoptInfo2: 'To adopt Milo, contact Happy Tails Animal Rescue at (555) 123-4567. Milo is neutered, healthy, and fully vaccinated.',
    petAge: 'Young',
    petGender: 'Male',
    petSize: 'Medium',
  ),

  PetDetailDataModel(
    petName: 'Shadow',
    petImage: 'assets/image/shadow_cat.jpg',
    petType: 'Cats',
    distanceFromPet: '2.8km',
    petBreed: 'Sphynx',
    petOrganization: 'Gentle Paws',
    petDescription: 'Shadow is a beautiful Russian Blue with a soft, velvety gray coat and calm, serene eyes. Known for his quiet and gentle nature, Shadow enjoys a peaceful environment.',
    petDescription2: 'He is a bit shy at first but warms up with patience and care. Once comfortable, Shadow becomes very affectionate and loves lounging in cozy spots around the home.',
    petOrganizationAddress: '555 Peaceful Way, Boston, MA 02101',
    petOrganizationImage: '',
    petAdoptInfo: 'Shadow would thrive in a quiet home with an adopter who values his calm presence. He is best suited to a low-stress environment where he can feel safe and loved.',
    petAdoptInfo2: 'Contact Gentle Paws at (555) 888-9999 for adoption inquiries. Shadow is neutered, vaccinated, and healthy.',
    petAge: 'Adult',
    petGender: 'Male',
    petSize: 'Medium',
  ),

  PetDetailDataModel(
    petName: 'Oliver',
    petImage: 'assets/image/oliver_cat.jpg',
    petType: 'Cats',
    distanceFromPet: '3.1km',
    petBreed: 'British Shorthair',
    petOrganization: 'Whiskers & Paws Shelter',
    petDescription: 'Oliver is a British Shorthair with a luxurious, fluffy coat and captivating gold eyes.',
    petDescription2: 'Oliver has a mellow, friendly demeanor. She loves being around people and enjoys curling up beside her favorite humans. She also has a playful side, especially when there are toys involved.',
    petOrganizationAddress: '222 Kitty Lane, Seattle, WA 98101',
    petOrganizationImage: '',
    petAdoptInfo: 'Oliver is looking for a loving home where she can be pampered and showered with attention. She\'ll thrive in a household that can provide both companionship and playtime.',
    petAdoptInfo2: 'To adopt Oliver, contact Whiskers & Paws Shelter at (555) 777-1212. She is neutered, vaccinated, and in excellent health.',
    petAge: 'Young',
    petGender: 'Female',
    petSize: 'Small',
  ),


    //dog
    PetDetailDataModel(
      petName: 'Luna', 
      petImage: 'assets/image/luna_dog.jpg', 
      petType: 'Dogs', 
      distanceFromPet: '1.2km', 
      petBreed: 'Chihuahua', 
      petOrganization: 'Paws & Love Shelter', 
      petDescription: 'Luna is a lovely Chihuahua and this gentle dog is known for her calm demeanor and loves lounging in cozy spots.', 
      petDescription2: 'Luna enjoys a peaceful environment and gentle petting sessions. Though a bit shy initially, she warms up quickly and shows affection to those she trusts.', 
      petOrganizationAddress: '456 Lane, Austin, TX 78701', 
      petOrganizationImage: '',
      petAdoptInfo: 'Luna would thrive in a home that offers stability and gentle companionship. She\'s looking for a loving family to share her calm and affectionate nature with.', 
      petAdoptInfo2: 'To adopt Luna, contact Paws & Love Shelter at (555) 654-3210. She is neutered, vaccinated, and in excellent health.',
      petAge: 'Young', 
      petGender: 'Female', 
      petSize: 'Small', 
    ),

    PetDetailDataModel(
      petName: 'Rusty',
      petImage: 'assets/image/rusty_dog.png',
      petType: 'Dogs',
      distanceFromPet: '1.2km',
      petBreed: 'Welsh Corgi',
      petOrganization: 'Whiskers & Paws Shelter',
      petDescription: 'Rusty is a cute and lovely Welshi Corgi.',
      petDescription2: 'Rusty has a mellow, friendly demeanor. She loves being around people and enjoys curling up beside her favorite humans. She also has a playful side, especially when there are toys involved.',
      petOrganizationAddress: '222 S Lane, Seattle, WA 98101',
      petOrganizationImage: '',
      petAdoptInfo: 'Rusty is looking for a loving home where she can be pampered and showered with attention. She\'ll thrive in a household that can provide both companionship and playtime.',
      petAdoptInfo2: 'To adopt Rusty, contact Whiskers & Paws Shelter at (555) 777-1212. She is neutered, vaccinated, and in excellent health.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Medium',
    ),

    PetDetailDataModel(
      petName: 'Maverick',
      petImage: 'assets/image/maverick_dog.png',
      petType: 'Dogs',
      distanceFromPet: '1.7km',
      petBreed: 'Great Dane',
      petOrganization: 'Whiskers & Paws Shelter',
      petDescription: 'Maverick is a cute and lovely Great Dane.',
      petDescription2: 'Maverick has a mellow, friendly demeanor. He loves adventure and enjoys curling up beside his favorite humans. He also has a playful side, especially when there are toys involved.',
      petOrganizationAddress: '222 S Lane, Seattle, WA 98101',
      petOrganizationImage: '',
      petAdoptInfo: 'Maverick is looking for a loving home where he can be pampered and showered with attention. He\'ll thrive in a household that can provide both companionship and playtime.',
      petAdoptInfo2: 'To adopt Maverick, contact Whiskers & Paws Shelter at (555) 777-1212. He is neutered, vaccinated, and in excellent health.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Large',
    ),

    PetDetailDataModel(
      petName: 'Scout',
      petImage: 'assets/image/scout_dog.png',
      petType: 'Dogs',
      distanceFromPet: '1.7km',
      petBreed: 'Afghan Hound',
      petOrganization: 'Happy Tails Animal Rescue',
      petDescription: 'Scout is a cute and lovely Afghan Hound.',
      petDescription2: 'Scout has a mellow, friendly demeanor. She loves adventure and enjoys curling up beside her favorite humans. She also has a playful side, especially when there are toys involved.',
      petOrganizationAddress: '123 Paws Street. NYC, NY 10001',
      petOrganizationImage: '',
      petAdoptInfo: 'Scout is looking for a loving home where she can be pampered and showered with attention. She\'ll thrive in a household that can provide both companionship and playtime.',
      petAdoptInfo2: 'To adopt Scout, contact Happy Tails Animal Rescue at (555) 123-4567. She is neutered, vaccinated, and in excellent health.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Large',
    ),

    PetDetailDataModel(
      petName: 'Comet',
      petImage: 'assets/image/comet_dog.png',
      petType: 'Dogs',
      distanceFromPet: '2.4km',
      petBreed: 'Jack Russell Terrier',
      petOrganization: 'Happy Tails Animal Rescue',
      petDescription: 'Comet is a cute and lovely Great Dane.',
      petDescription2: 'Comet has a mellow, friendly demeanor. He loves adventure and enjoys curling up beside his favorite humans. He also has a playful side, especially when there are toys involved.',
      petOrganizationAddress: '123 Paws Street. NYC, NY 10001',
      petOrganizationImage: '',
      petAdoptInfo: 'Comet is looking for a loving home where he can be pampered and showered with attention. He\'ll thrive in a household that can provide both companionship and playtime.',
      petAdoptInfo2: 'To adopt Maverick, contact Happy Tails Animal Rescue at (555) 123-4567. He is neutered, vaccinated, and in excellent health.',
      petAge: 'Comet',
      petGender: 'Male',
      petSize: 'Large',
    ),

    PetDetailDataModel(
      petName: 'Pepper',
      petImage: 'assets/image/pepper_dog.png',
      petType: 'Dogs',
      distanceFromPet: '2.4km',
      petBreed: 'American Eskimo',
      petOrganization: 'FurEver Friends',
      petDescription: 'Pepper has a white and crystal clear fur.',
      petDescription2: 'Pepper has a mellow, friendly demeanor. He loves adventure and enjoys curling up beside his favorite humans. He also has a playful side, especially when there are toys involved.',
      petOrganizationAddress: '789 Persian Alley, Orlando, FL 32801',
      petOrganizationImage: '',
      petAdoptInfo: 'Pepper is looking for a loving home where he can be pampered and showered with attention. He\'ll thrive in a household that can provide both companionship and playtime.',
      petAdoptInfo2: 'To adopt Pepper, contact FurEver Friends at (555) 101-2020. He is neutered, vaccinated, and in excellent health.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Large',
    ),
    
    //rabbits
    PetDetailDataModel(
      petName: 'Conttontail',
      petImage: 'assets/image/cottontail_rabbit.png',
      petType: 'Rabbits',
      distanceFromPet: '1.5km',
      petBreed: 'Beveren',
      petOrganization: 'Happy Tails Animal Rescue',
      petDescription: 'Cottontail is a cute and lovely Beveren rabbit.',
      petDescription2: 'Cottontail has a mellow, friendly demeanor. He loves adventure and enjoys curling up beside his favorite humans. He also has a playful side, especially when there are toys involved.',
      petOrganizationAddress: '123 Paws Street. NYC, NY 10001',
      petOrganizationImage: '',
      petAdoptInfo: 'Cottontail is looking for a loving home where he can be pampered and showered with attention.',
      petAdoptInfo2: 'To adopt Conttontail, contact Happy Tails Animal Rescue at (555) 123-4567. He is neutered, vaccinated, and in excellent health.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Clover',
      petImage: 'assets/image/clover_rabbit.png',
      petType: 'Rabbits',
      distanceFromPet: '1.2km',
      petBreed: 'Fauve de Bourgo',
      petOrganization: 'Bunny Love Rescue',
      petDescription: 'Clover is a sweet Holland Lop rabbit with a soft, fluffy coat and adorable floppy ears. She is curious and loves gentle petting and cuddles.',
      petDescription2: 'Clover enjoys hopping around and exploring new spaces. She has a calm, gentle temperament and will quickly bond with her new family.',
      petOrganizationAddress: '654 Bunny Blvd, Portland, OR 97201',
      petOrganizationImage: '',
      petAdoptInfo: 'Clover would thrive in a calm environment where she can have space to explore. She\'s looking for a gentle, loving family who will give her the care she deserves.',
      petAdoptInfo2: 'To adopt Clover, reach out to Bunny Love Rescue at (555) 333-4444. She is spayed, healthy, and ready for her forever home.',
      petAge: 'Young',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Hazel',
      petImage: 'assets/image/hazel_rabbit.png',
      petType: 'Rabbits',
      distanceFromPet: '1.2km',
      petBreed: 'Dwarf Angora',
      petOrganization: 'Bunny Love Rescue',
      petDescription: 'Hazel is a sweet rabbit with a soft, fluffy coat and adorable floppy ears. She is curious and loves gentle petting and cuddles.',
      petDescription2: 'Hazel enjoys hopping around and exploring new spaces. She has a calm, gentle temperament and will quickly bond with her new family.',
      petOrganizationAddress: '654 Bunny Blvd, Portland, OR 97201',
      petOrganizationImage: '',
      petAdoptInfo: 'Hazel would thrive in a calm environment where she can have space to explore. She\'s looking for a gentle, loving family who will give her the care she deserves.',
      petAdoptInfo2: 'To adopt Hazel, reach out to Bunny Love Rescue at (555) 333-4444. She is spayed, healthy, and ready for her forever home.',
      petAge: 'Young',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Pippin',
      petImage: 'assets/image/pippin_rabbit.png',
      petType: 'Rabbits',
      distanceFromPet: '2.1km',
      petBreed: 'Polish',
      petOrganization: 'Bunny Love Rescue',
      petDescription: 'Pippin is a sweet rabbit with a soft, fluffy coat and adorable floppy ears. He is curious and loves gentle petting and cuddles.',
      petDescription2: 'Pippin enjoys hopping around and exploring new spaces. He has a calm, gentle temperament and will quickly bond with his new family.',
      petOrganizationAddress: '654 Bunny Blvd, Portland, OR 97201',
      petOrganizationImage: '',
      petAdoptInfo: 'Pippin would thrive in a calm environment where he can have space to explore. He\'s looking for a gentle, loving family who will give his the care he deserves.',
      petAdoptInfo2: 'To adopt Clover, reach out to Bunny Love Rescue at (555) 333-4444. He is spayed, healthy, and ready for his forever home.',
      petAge: 'Young',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Whiskers',
      petImage: 'assets/image/whiskers_rabbit.png',
      petType: 'Rabbits',
      distanceFromPet: '2.4km',
      petBreed: 'Tan',
      petOrganization: 'Bunny Love Rescue',
      petDescription: 'Whiskers is a sweet Tan rabbit with a soft, fluffy coat and adorable floppy ears.',
      petDescription2: 'Whiskers enjoys hopping around and exploring new spaces. She has a calm, gentle temperament and will quickly bond with her new family.',
      petOrganizationAddress: '654 Bunny Blvd, Portland, OR 97201',
      petOrganizationImage: '',
      petAdoptInfo: 'Whiskers would thrive in a calm environment where she can have space to explore. She\'s looking for a gentle, loving family who will give her the care she deserves.',
      petAdoptInfo2: 'To adopt Whiskers, reach out to Bunny Love Rescue at (555) 333-4444. She is spayed, healthy, and ready for her forever home.',
      petAge: 'Young',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Muffin',
      petImage: 'assets/image/muffin_rabbit.png',
      petType: 'Rabbits',
      distanceFromPet: '2.4km',
      petBreed: 'Netherland Dwarf',
      petOrganization: 'Happy Tails Animal Rescue',
      petDescription: 'Muffin is a lovely rabbit with a soft, fluffy coat and adorable floppy ears.',
      petDescription2: 'Muffin enjoys hopping around and exploring new spaces. He has a calm, gentle temperament and will quickly bond with his new family.',
      petOrganizationAddress: '123 Paws Street. NYC, NY 10001',
      petOrganizationImage: '',
      petAdoptInfo: 'Muffin would thrive in a calm environment where he can have space to explore. He\'s looking for a gentle, loving family who will give his the care she deserves.',
      petAdoptInfo2: 'To adopt Muffin, reach out to Happy Tails Animal Rescue at (555) 123-4567. He is spayed, healthy, and ready for his forever home.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Small',
    ),

    //birds
    PetDetailDataModel(
      petName: 'Tweenty',
      petImage: 'assets/image/tweety_bird.jpg',
      petType: 'Birds',
      distanceFromPet: '0.8km',
      petBreed: 'Canary',
      petOrganization: 'Feline Friends Rescue',
      petDescription: 'Tweenty is a cheerful with bright yellow feathers Canary. Known for his lively chirping and playful behavior, he loves to interact and explore.',
      petDescription2: 'Tweenty enjoys singing and mimicking sounds. He is happiest in a cage filled with toys and perches and loves being around people. He\'s easy to care for and a joy to watch.',
      petOrganizationAddress: '753 Andrea Street, Ohio, OH 43029',
      petOrganizationImage: '',
      petAdoptInfo: 'Tweenty is looking for a warm home where he can sing and play to his heart\'s content. He\'ll thrive with an adopter who appreciates his vibrant personality.',
      petAdoptInfo2: 'To adopt Tweenty, contact Feline Friends Rescue at (555) 654-3210. Tweenty is healthy and up-to-date on all necessary care.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Skye',
      petImage: 'assets/image/skye_bird.jpg',
      petType: 'Birds',
      distanceFromPet: '1.2km',
      petBreed: 'Parrot',
      petOrganization: 'Wings of Love Rescue',
      petDescription: 'Skye is a cheerful with bright feathers. Known for his lively chirping and playful behavior, he loves to interact and explore.',
      petDescription2: 'Skye enjoys singing and mimicking sounds. He is happiest in a cage filled with toys and perches and loves being around people. He\'s easy to care for and a joy to watch.',
      petOrganizationAddress: '123 Feather Lane, Miami, FL 33101',
      petOrganizationImage: '',
      petAdoptInfo: 'Skye is looking for a warm home where he can sing and play to his heart\'s content. He\'ll thrive with an adopter who appreciates his vibrant personality.',
      petAdoptInfo2: 'To adopt Skye, contact Wings of Love Rescue at (555) 222-3333. Skye is healthy and up-to-date on all necessary care.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Kiwi',
      petImage: 'assets/image/kiwi_bird.jpg',
      petType: 'Birds',
      distanceFromPet: '1.6km',
      petBreed: 'Budgerigar',
      petOrganization: 'Happy Tails Animal Rescue',
      petDescription: 'Kiwi is a cheerful with bright blue feathers. Known for her lively chirping and playful behavior, she loves to interact and explore.',
      petDescription2: 'Kiwi enjoys singing and mimicking sounds. She is happiest in a cage filled with toys and perches and loves being around people. She\'s easy to care for and a joy to watch.',
      petOrganizationAddress: '123 Paws Street. NYC, NY 10001',
      petOrganizationImage: '',
      petAdoptInfo: 'Kiwi is looking for a warm home where she can sing and play to her heart\'s content. She\'ll thrive with an adopter who appreciates her vibrant personality.',
      petAdoptInfo2: 'To adopt Kiwi, contact Happy Tails Animal Rescue at (555) 123-4567. Kiwi is healthy and up-to-date on all necessary care.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Sunny',
      petImage: 'assets/image/sunny_bird.png',
      petType: 'Birds',
      distanceFromPet: '2.0km',
      petBreed: 'Cockatiel',
      petOrganization: 'Wings of Love Rescue',
      petDescription: 'Sunny is a cheerful with bright feathers. Known for her lively chirping and playful behavior, she loves to interact and explore.',
      petDescription2: 'Sunny enjoys singing and mimicking sounds. She is happiest in a cage filled with toys and perches and loves being around people. She\'s easy to care for and a joy to watch.',
      petOrganizationAddress: '123 Feather Lane, Miami, FL 33101',
      petOrganizationImage: '',
      petAdoptInfo: 'Sunny is looking for a warm home where she can sing and play to her heart\'s content. She\'ll thrive with an adopter who appreciates her vibrant personality.',
      petAdoptInfo2: 'To adopt Sunny, contact Wings of Love Rescue at (555) 222-3333. Sunny is healthy and up-to-date on all necessary care.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Rio',
      petImage: 'assets/image/rio_bird.jpg',
      petType: 'Birds',
      distanceFromPet: '2.0km',
      petBreed: 'Macaw',
      petOrganization: 'Wings of Love Rescue',
      petDescription: 'Rio is a cheerful with bright feathers. Known for his lively chirping and playful behavior, he loves to interact and explore.',
      petDescription2: 'Rio enjoys singing and mimicking sounds. He is happiest in a cage filled with toys and perches and loves being around people. He\'s easy to care for and a joy to watch.',
      petOrganizationAddress: '123 Feather Lane, Miami, FL 33101',
      petOrganizationImage: '',
      petAdoptInfo: 'Rio is looking for a warm home where he can sing and play to his heart\'s content. He\'ll thrive with an adopter who appreciates his vibrant personality.',
      petAdoptInfo2: 'To adopt Rio, contact Wings of Love Rescue at (555) 222-3333. Rio is healthy and up-to-date on all necessary care.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Medium',
    ),

    PetDetailDataModel(
      petName: 'Peppy',
      petImage: 'assets/image/peppy_bird.jpg',
      petType: 'Birds',
      distanceFromPet: '2.6km',
      petBreed: 'Lovebird',
      petOrganization: 'Wings of Love Rescue',
      petDescription: 'Peppy is a cheerful with bright orange and green feathers. Known for his lively chirping and playful behavior, he loves to interact and explore.',
      petDescription2: 'Peppy enjoys singing and mimicking sounds. He is happiest in a cage filled with toys and perches and loves being around people. He\'s easy to care for and a joy to watch.',
      petOrganizationAddress: '123 Feather Lane, Miami, FL 33101',
      petOrganizationImage: '',
      petAdoptInfo: 'Peppy is looking for a warm home where he can sing and play to his heart\'s content. He\'ll thrive with an adopter who appreciates his vibrant personality.',
      petAdoptInfo2: 'To adopt Peppy, contact Wings of Love Rescue at (555) 222-3333. Peppy is healthy and up-to-date on all necessary care.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Small',
    ),


    //Reptiles
    PetDetailDataModel(
      petName: 'Spike',
      petImage: 'assets/image/spike_reptile.jpg',
      petType: 'Reptiles',
      distanceFromPet: '1.0km',
      petBreed: 'Bearded Dragon',
      petOrganization: 'Reptile Haven Rescue',
      petDescription: 'Spike is a friendly Bearded Dragon with a relaxed personality and striking orange scales. He\'s curious and enjoys basking under his heat lamp.',
      petDescription2: 'Spike loves being held and interacting with his human friends. He\'s easygoing, making him perfect for a beginner reptile owner who\'s looking for a calm companion.',
      petOrganizationAddress: '123 Scale Street, Phoenix, AZ 85001',
      petOrganizationImage: '',
      petAdoptInfo: 'Spike is looking for a warm, loving home with an enclosure where he can bask and explore. He\'ll thrive with an owner who can provide a stable habitat.',
      petAdoptInfo2: 'For adoption inquiries, contact Reptile Haven Rescue at (555) 123-4567. Spike is healthy and accustomed to handling.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Medium',
    ),

    PetDetailDataModel(
      petName: 'Slyther',
      petImage: 'assets/image/slyther_reptile.jpg',
      petType: 'Reptiles',
      distanceFromPet: '1.4km',
      petBreed: 'Ball Python',
      petOrganization: 'Scales Sanctuary',
      petDescription: 'Slyther is a beautiful Ball Python with a spotted yellow and brown pattern. Known for her gentle nature, she\'s a low-maintenance pet that enjoys relaxing in her habitat.',
      petDescription2: 'Slyther is active during the evening and loves exploring small hideouts in her tank. She\'s ideal for an owner who enjoys watching her unique behavior and provides a quiet environment.',
      petOrganizationAddress: '456 Reptile Road, Denver, CO 80201',
      petOrganizationImage: '',
      petAdoptInfo: 'Slyther is looking for a calm, stable environment with a tank setup that includes hiding spots and heat control. She\'ll thrive with a caring, observant owner.',
      petAdoptInfo2: 'Contact Scales Sanctuary at (555) 234-5678 for more details. Slyther is in excellent health and easy to care for.',
      petAge: 'Young',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Cleo',
      petImage: 'assets/image/cleo_reptile.jpg',
      petType: 'Reptiles',
      distanceFromPet: '1.7km',
      petBreed: 'Leopard Gecko',
      petOrganization: 'Scales Sanctuary',
      petDescription: 'Cleo is a beautiful Leopard Gecko with a spotted yellow pattern. Known for his gentle nature, he\'s a low-maintenance pet that enjoys relaxing in his habitat.',
      petDescription2: 'Cleo is active during the evening and loves exploring small hideouts in his tank. He\'s ideal for an owner who enjoys watching his unique behavior and provides a quiet environment.',
      petOrganizationAddress: '456 Reptile Road, Denver, CO 80201',
      petOrganizationImage: '',
      petAdoptInfo: 'Cleo is looking for a calm, stable environment with a tank setup that includes hiding spots and heat control. He\'ll thrive with a caring, observant owner.',
      petAdoptInfo2: 'Contact Scales Sanctuary at (555) 234-5678 for more details. Cleo is in excellent health and easy to care for.',
      petAge: 'Young',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Rango',
      petImage: 'assets/image/rango_reptile.jpg',
      petType: 'Reptiles',
      distanceFromPet: '2.1km',
      petBreed: 'Chameleon',
      petOrganization: 'Reptile Haven Rescue',
      petDescription: 'Rango is a friendly Chameleon with a relaxed personality and striking green scales. He\'s curious and enjoys basking under his heat lamp.',
      petDescription2: 'Rango loves being held and interacting with his human friends. He\'s easygoing, making him perfect for a beginner reptile owner who\'s looking for a calm companion.',
      petOrganizationAddress: '123 Scale Street, Phoenix, AZ 85001',
      petOrganizationImage: '',
      petAdoptInfo: 'Rango is looking for a warm, loving home with an enclosure where he can bask and explore. He\'ll thrive with an owner who can provide a stable habitat.',
      petAdoptInfo2: 'For adoption inquiries, contact Reptile Haven Rescue at (555) 123-4567. Rango is healthy and accustomed to handling.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Medium',
    ),

    PetDetailDataModel(
      petName: 'Mushu',
      petImage: 'assets/image/mushu_reptile.jpg',
      petType: 'Reptiles',
      distanceFromPet: '2.5km',
      petBreed: 'Chinese Water Dragon',
      petOrganization: 'Reptile Haven Rescue',
      petDescription: 'Mushu is a friendly Chinese Water Dragon with a relaxed personality and striking green scales. He\'s curious and enjoys basking under his heat lamp.',
      petDescription2: 'Mushu loves being held and interacting with his human friends. He\'s easygoing, making him perfect for a beginner reptile owner who\'s looking for a calm companion.',
      petOrganizationAddress: '123 Scale Street, Phoenix, AZ 85001',
      petOrganizationImage: '',
      petAdoptInfo: 'Rango is looking for a warm, loving home with an enclosure where he can bask and explore. He\'ll thrive with an owner who can provide a stable habitat.',
      petAdoptInfo2: 'For adoption inquiries, contact Reptile Haven Rescue at (555) 123-4567. Rango is healthy and accustomed to handling.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Medium',
    ),

    PetDetailDataModel(
      petName: 'Tango',
      petImage: 'assets/image/tango_reptile.jpg',
      petType: 'Reptiles',
      distanceFromPet: '2.9km',
      petBreed: 'Corn Snake',
      petOrganization: 'Feline Friends Rescue',
      petDescription: 'Tango is a friendly Corn Snake with a relaxed personality and striking green scales. She\'s curious and enjoys basking under her heat lamp.',
      petDescription2: 'Tango loves being held and interacting with her human friends. She\'s easygoing, making her perfect for a beginner reptile owner who\'s looking for a calm companion.',
      petOrganizationAddress: '753 Andrea Street, Ohio, OH 43029',
      petOrganizationImage: '',
      petAdoptInfo: 'Tango is looking for a warm, loving home with an enclosure where she can bask and explore. She\'ll thrive with an owner who can provide a stable habitat.',
      petAdoptInfo2: 'For adoption inquiries, contact Feline Friends Rescue at (555) 654-3210. Tango is healthy and accustomed to handling.',
      petAge: 'Young',
      petGender: 'Female',
      petSize: 'Small',
    ),
   
   //fish
    PetDetailDataModel(
      petName: 'Goldie',
      petImage: 'assets/image/goldie_fish.jpg',
      petType: 'Fish',
      distanceFromPet: '1.1km',
      petBreed: 'Goldfish',
      petOrganization: 'Fin Friends Rescue',
      petDescription: 'Goldie is a Goldfish with a dazzling orange tail that fans out like a feather. Known for his striking colors, he\'s a low-maintenance pet that loves to explore.',
      petDescription2: 'Goldie enjoys a calm tank with hiding spots and plants to swim around. He\'s perfect for a beginner fish enthusiast looking for a beautiful, easy-to-care-for companion.',
      petOrganizationAddress: 'c',
      petOrganizationImage: '',
      petAdoptInfo: 'Goldie would thrive in a small tank with gentle filtration. He\'s ideal for a peaceful home where he can swim in a relaxing environment.',
      petAdoptInfo2: 'For adoption inquiries, contact Fin Friends Rescue at (555) 111-2222. Goldie is healthy and accustomed to his tank setup.',
      petAge: 'Young',
      petGender: 'Male',
      petSize: 'Small',
    ),


    PetDetailDataModel(
      petName: 'Bubbles',
      petImage: 'assets/image/bubbles_fish.png',
      petType: 'Fish',
      distanceFromPet: '1.4km',
      petBreed: 'Betta Fish',
      petOrganization: 'Fin Friends Rescue',
      petDescription: 'Bubbles is a vibrant Betta Fish with a dazzling blue and red tail that fans out like a feather. Known for his striking colors, he\'s a low-maintenance pet that loves to explore.',
      petDescription2: 'Bubbles enjoys a calm tank with hiding spots and plants to swim around. He\'s perfect for a beginner fish enthusiast looking for a beautiful, easy-to-care-for companion.',
      petOrganizationAddress: '123 Aqua Ave, Seattle, WA 98101',
      petOrganizationImage: '',
      petAdoptInfo: 'Bubbles would thrive in a small tank with gentle filtration. He\'s ideal for a peaceful home where he can swim in a relaxing environment.',
      petAdoptInfo2: 'For adoption inquiries, contact Fin Friends Rescue at (555) 111-2222. Bubbles is healthy and accustomed to his tank setup.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Splash',
      petImage: 'assets/image/splash_fish.jpg',
      petType: 'Fish',
      distanceFromPet: '1.8km',
      petBreed: 'Guppy',
      petOrganization: 'Freshwater Friends Rescue',
      petDescription: 'Splash is a lively Guppy with brilliant purple and pink patterns. Small and playful, he\'s known for his active swimming and curious personality.',
      petDescription2: 'Splash enjoys swimming in groups and exploring his tank. He\'s easy to care for and adds color and energy to any freshwater aquarium.',
      petOrganizationAddress: '321 Waterway, Austin, TX 78701',
      petOrganizationImage: '',
      petAdoptInfo: 'Splash would thrive in a community tank with other peaceful fish. He\'s perfect for a beginner or someone with a well-established freshwater aquarium.',
      petAdoptInfo2: 'For adoption inquiries, contact Freshwater Friends Rescue at (555) 777-8888. Splash is healthy and ready to join a new tank.',
      petAge: 'Young',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Flipper',
      petImage: 'assets/image/flipper_fish.jpg',
      petType: 'Fish',
      distanceFromPet: '2.0km',
      petBreed: 'Clownfish',
      petOrganization: 'Freshwater Friends Rescue',
      petDescription: 'Flipper is a lively Clownfish. Small and playful, he\'s known for his active swimming and curious personality.',
      petDescription2: 'Flipper enjoys swimming in groups and exploring his tank. He\'s easy to care for and adds color and energy to any freshwater aquarium.',
      petOrganizationAddress: '321 Waterway, Austin, TX 78701',
      petOrganizationImage: '',
      petAdoptInfo: 'Flipper would thrive in a community tank with other peaceful fish. He\'s perfect for a beginner or someone with a well-established freshwater aquarium.',
      petAdoptInfo2: 'For adoption inquiries, contact Freshwater Friends Rescue at (555) 777-8888. Flipper is healthy and ready to join a new tank.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Coral',
      petImage: 'assets/image/coral_fish.jpg',
      petType: 'Fish',
      distanceFromPet: '2.4km',
      petBreed: 'Tetra',
      petOrganization: 'Freshwater Friends Rescue',
      petDescription: 'Coral is a lively Tetra. Small and playful, she\'s known for her active swimming and curious personality.',
      petDescription2: 'Coral enjoys swimming in groups and exploring her tank. She\'s easy to care for and adds color and energy to any freshwater aquarium.',
      petOrganizationAddress: '321 Waterway, Austin, TX 78701',
      petOrganizationImage: '',
      petAdoptInfo: 'Coral would thrive in a community tank with other peaceful fish. She\'s perfect for a beginner or someone with a well-established freshwater aquarium.',
      petAdoptInfo2: 'For adoption inquiries, contact Freshwater Friends Rescue at (555) 777-8888. Coral is healthy and ready to join a new tank.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Finley',
      petImage: 'assets/image/finley_fish.jpg',
      petType: 'Fish',
      distanceFromPet: '2.8km',
      petBreed: 'Angelfish',
      petOrganization: 'Happy Tails Animal Rescue',
      petDescription: 'Finley is a stunning Angelfish with delicate yellow and black stripes. Graceful and serene, she brings elegance to any aquarium.',
      petDescription2: 'Finley loves a calm environment with tall plants to swim around. She does well with other peaceful fish and requires a tank with stable water conditions.',
      petOrganizationAddress: '123 Paws Street. NYC, NY 10001',
      petOrganizationImage: '',
      petAdoptInfo: 'Finley would thrive in a peaceful aquarium with tank mates that share her calm nature. She\'s ideal for an experienced fish keeper.',
      petAdoptInfo2: 'To inquire about adopting Finley, reach out to Happy Tails Animal Rescue at (555) 123-4567. Finley is healthy and accustomed to community tanks.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Small',
    ),

    //primate
    PetDetailDataModel(
      petName: 'Chichi',
      petImage: 'assets/image/chichi_primate.jpg',
      petType: 'Primates',
      distanceFromPet: '1.5km',
      petBreed: 'Chimpanzee',
      petOrganization: 'Primate Haven Rescue',
      petDescription: 'Chichi is an energetic Chimpanzee known for his intelligence and playful nature. He\'s curious and loves interacting with people and toys.',
      petDescription2: 'Chichi enjoys problem-solving games, climbing, and exploring new environments. He\'s a highly social primate and thrives on mental stimulation and interaction.',
      petOrganizationAddress: '123 Jungle Drive, Orlando, FL 32801',
      petOrganizationImage: '',
      petAdoptInfo: 'Chichi requires a large, enriched environment where he can engage his active mind. He needs a dedicated owner who can provide ample time and attention.',
      petAdoptInfo2: 'For adoption inquiries, contact Primate Haven Rescue at (555) 111-2222. Chichi is in good health, vaccinated, and ready for a stimulating home.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Medium',
    ),

    PetDetailDataModel(
      petName: 'Bongo',
      petImage: 'assets/image/bongo_primate.jpg',
      petType: 'Primates',
      distanceFromPet: '1.8km',
      petBreed: 'Baboon',
      petOrganization: 'Primate Haven Rescue',
      petDescription: 'Bongo is a small Baboon known for her intelligence and playful nature. She\'s curious and loves interacting with people and toys.',
      petDescription2: 'Bongo enjoys problem-solving games, climbing, and exploring new environments. She\'s a highly social primate and thrives on mental stimulation and interaction.',
      petOrganizationAddress: '123 Jungle Drive, Orlando, FL 32801',
      petOrganizationImage: '',
      petAdoptInfo: 'Bongo requires a large, enriched environment where she can engage her active mind. She needs a dedicated owner who can provide ample time and attention.',
      petAdoptInfo2: 'For adoption inquiries, contact Primate Haven Rescue at (555) 111-2222. Bongo is in good health, vaccinated, and ready for a stimulating home.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Lunna',
      petImage: 'assets/image/luna_primate.jpg',
      petType: 'Primates',
      distanceFromPet: '2.1km',
      petBreed: 'Lemur',
      petOrganization: 'Exotic Primates Society',
      petDescription: 'Luna is a striking Lemur. He\'s known for his intelligence and enjoys climbing and foraging.',
      petDescription2: 'Luna loves a complex environment with climbing structures, hidden treats, and toys to keep him engaged. He\'s best suited for a home that can meet his active needs.',
      petOrganizationAddress: '456 Primate Drive, Austin, TX 78701',
      petOrganizationImage: '',
      petAdoptInfo: 'Luna requires a large, secure space with opportunities for climbing and exploring. He\'s perfect for an owner who values interaction and mental enrichment.',
      petAdoptInfo2: 'For adoption inquiries, contact Exotic Primates Society at (555) 999-0000. Luna is healthy, well-socialized, and ready for his forever home.',
      petAge: 'Young',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Koko',
      petImage: 'assets/image/koko_primate.jpg',
      petType: 'Primates',
      distanceFromPet: '2.5km',
      petBreed: 'Tamarin',
      petOrganization: 'Exotic Primates Society',
      petDescription: 'Koko is a striking Tamarin with a long tail and expressive eyes. He\'s known for his intelligence and enjoys climbing and foraging.',
      petDescription2: 'Koko loves a complex environment with climbing structures, hidden treats, and toys to keep him engaged. He\'s best suited for a home that can meet his active needs.',
      petOrganizationAddress: '456 Primate Drive, Austin, TX 78701',
      petOrganizationImage: '',
      petAdoptInfo: 'Koko requires a large, secure space with opportunities for climbing and exploring. He\'s perfect for an owner who values interaction and mental enrichment.',
      petAdoptInfo2: 'For adoption inquiries, contact Exotic Primates Society at (555) 999-0000. Koko is healthy, well-socialized, and ready for his forever home.',
      petAge: 'Young',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Taz',
      petImage: 'assets/image/taz_primate.jpg',
      petType: 'Primates',
      distanceFromPet: '2.8km',
      petBreed: 'Bushbaby',
      petOrganization: 'Exotic Animal Sanctuary',
      petDescription: 'Taz is a small, wide-eyed Bushbaby with a soft, velvety coat and a curious personality. Known for her large eyes and excellent jumping ability, she\'s an intriguing little primate.',
      petDescription2: 'Taz is nocturnal, so she\'s most active at night. She enjoys leaping between branches and foraging for treats hidden in her environment. Bushbabies are highly independent and prefer a quiet, calm atmosphere.',
      petOrganizationAddress: '678 Wildlife Avenue, Denver, CO 80201',
      petOrganizationImage: '',
      petAdoptInfo: 'Taz requires a secure, spacious enclosure with branches for climbing and jumping. She needs a dedicated caregiver who understands her nocturnal nature and can create a quiet, naturalistic habitat.',
      petAdoptInfo2: 'To inquire about adopting Taz, contact Exotic Animal Sanctuary at (555) 111-3333. Taz is healthy and has been cared for by experienced exotic animal handlers.',
      petAge: 'Young',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Zuri',
      petImage: 'assets/image/zuri_primate.jpg',
      petType: 'Primates',
      distanceFromPet: '3.0km',
      petBreed: 'Capuchin Monkey',
      petOrganization: 'Primate Rescue Center',
      petDescription: 'Zuri is a lively Capuchin Monkey with sharp intelligence and a playful spirit. Known for his quick learning ability, he\'s full of energy and curious about his surroundings.',
      petDescription2: 'Zuri thrives on mental stimulation and loves solving puzzles, playing with toys, and exploring his environment. He\'s a social primate who benefits from interactive play and requires a lot of engagement and attention.',
      petOrganizationAddress: '345 Jungle Path, Portland, OR 97201',
      petOrganizationImage: '',
      petAdoptInfo: 'Zuri needs a large, stimulating environment with interactive toys, climbing structures, and a dedicated caregiver who can spend ample time engaging with him. He\'s best suited for an adopter experienced in primate care.',
      petAdoptInfo2: 'For adoption inquiries, contact Primate Rescue Center at (555) 444-5555. Zuri is in excellent health, vaccinated, and accustomed to human interaction.',
      petAge: 'Adult',
      petGender: 'Male',
      petSize: 'Small',
    ),
 

    //other
    PetDetailDataModel(
      petName: 'Bessie',
      petImage: 'assets/image/bessie_cattle.jpg',
      petType: 'Other',
      distanceFromPet: '1.0km',
      petBreed: 'Holstein',
      petOrganization: 'Happy Tails Animal Rescue',
      petDescription: 'Bessie is a gentle Holstein cow with the classic black-and-white markings. She\'s calm and friendly, known for her sociable nature and her love for grazing in open fields.',
      petDescription2: 'Bessie enjoys interacting with other animals and people. She\'s happiest in a spacious pasture where she can freely roam and graze. Holsteins are known for their gentle disposition and are perfect for a farm-loving family.',
      petOrganizationAddress: '123 Paws Street. NYC, NY 10001',
      petOrganizationImage: '',
      petAdoptInfo: 'Bessie requires a large outdoor area to roam and graze and regular access to clean water and shelter. She\'s looking for a home that can provide daily care and attention.',
      petAdoptInfo2: 'Contact Happy Tails Animal Rescue at (555) 123-4567 for adoption inquiries. Bessie is healthy and has been vaccinated.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Large',
    ),

    PetDetailDataModel(
      petName: 'Shep',
      petImage: 'assets/image/shep_sheep.jpg',
      petType: 'Other',
      distanceFromPet: '1.5km',
      petBreed: 'Merino',
      petOrganization: 'Shepherd\'s Heart Farm',
      petDescription: 'Shep is a fluffy Merino sheep with soft, dense wool and a calm, docile nature. Known for their fine wool, Merinos are gentle and great around people.',
      petDescription2: 'Shep enjoys grazing with her flock and thrives in open pastures. She\'s a low-maintenance, friendly sheep perfect for anyone interested in small-scale farming or wool harvesting.',
      petOrganizationAddress: '123 Shepherd Road, Albany, NY 12201',
      petOrganizationImage: '',
      petAdoptInfo: 'Shep needs a secure, open area for grazing and regular shearing. She\'s best suited for a home that can provide the care required for wool sheep.',
      petAdoptInfo2: 'To adopt Shep, contact Shepherd\'s Heart Farm at (555) 303-4040. She\'s healthy, vaccinated, and ready for a loving home.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Medium',
    ),

    PetDetailDataModel(
      petName: 'Billy',
      petImage: 'assets/image/billy_goat.jpg',
      petType: 'Other',
      distanceFromPet: '2.0km',
      petBreed: 'Boer',
      petOrganization: 'Shepherd\'s Heart Farm',
      petDescription: 'Billy is a sturdy Boer goat with a distinctive white body and red head. He\'s friendly, active, and loves climbing and exploring his surroundings.',
      petDescription2: 'Boer goats are known for their strong build and playful nature. Billy thrives in an environment with plenty of space to roam and enjoys interacting with other goats and people.',
      petOrganizationAddress: '123 Shepherd Road, Albany, NY 12201',
      petOrganizationImage: '',
      petAdoptInfo: 'Billy would be happiest on a farm with space to roam and a few other goats for companionship. He needs an enclosure that\'s safe and spacious.',
      petAdoptInfo2: 'Contact Shepherd\'s Heart Farm at (555) 303-4040 to inquire about adopting Billy. He\'s healthy and well-socialized.',
      petAge: 'Young',
      petGender: 'Male',
      petSize: 'Medium',
    ),

    PetDetailDataModel(
      petName: 'Porky',
      petImage: 'assets/image/porky_ferrets.jpg',
      petType: 'Other',
      distanceFromPet: '2.5km',
      petBreed: 'Ferrets',
      petOrganization: 'Shepherd\'s Heart Farm',
      petDescription: 'Porky is a playful Ferret with a mischievous personality. Known for his curiosity, he loves exploring small spaces and engaging with interactive toys.',
      petDescription2: 'Ferrets are highly social and enjoy time outside of their cage for play. Porky needs regular interaction to stay happy and would do best with an attentive owner.',
      petOrganizationAddress: '123 Shepherd Road, Albany, NY 12201',
      petOrganizationImage: '',
      petAdoptInfo: 'Porky needs a secure cage with plenty of room and daily playtime outside. He\'d thrive in a home that can provide lots of mental stimulation.',
      petAdoptInfo2: 'To adopt Porky, reach out to Shepherd\'s Heart Farm at (555) 303-4040. He\'s healthy, vaccinated, and ready for a loving home.',
      petAge: 'Young',
      petGender: 'Male',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Nibbles',
      petImage: 'assets/image/nibbles_guinea_pig.jpg',
      petType: 'Other',
      distanceFromPet: '2.8km',
      petBreed: 'Abyssinian Guinea Pig',
      petOrganization: 'FurEver Friends',
      petDescription: 'Nibbles is a cute Abyssinian Guinea Pig with a rosette-patterned coat. She\'s friendly, social, and loves nibbling on fresh veggies.',
      petDescription2: 'Guinea pigs like Nibbles enjoy company and are happiest in pairs or groups. She loves to explore her enclosure and is gentle and easy to handle.',
      petOrganizationAddress: '789 Persian Alley, Orlando, FL 32801',
      petOrganizationImage: '',
      petAdoptInfo: 'Nibbles needs a spacious cage, fresh bedding, and daily playtime. She\'s perfect for someone looking for a low-maintenance companion.',
      petAdoptInfo2: 'Contact FurEver Friends at (555) 101-2020 to learn about adopting Nibbles. She\'s healthy and ready for her new home.',
      petAge: 'Young',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Hammy',
      petImage: 'assets/image/hammy_hamster.JPG',
      petType: 'Other',
      distanceFromPet: '3.0km',
      petBreed: 'Syrian Hamster',
      petOrganization: 'FurEver Friends',
      petDescription: 'Hammy is an adorable Syrian Hamster with golden fur and a curious nature. Known for being solitary and active at night, Hammy enjoys burrowing and exploring.',
      petDescription2: 'Hammy needs a spacious, multi-level cage with tunnels and an exercise wheel to keep her entertained. Syrian Hamsters are best housed alone due to their territorial nature.',
      petOrganizationAddress: '789 Persian Alley, Orlando, FL 32801',
      petOrganizationImage: '',
      petAdoptInfo: 'Hammy requires a quiet, secure cage with enrichment and regular handling. She\'s ideal for an owner who appreciates small, solitary pets.',
      petAdoptInfo2: 'For adoption inquiries, contact FurEver Friends at (555) 101-2020. Hammy is healthy and accustomed to handling.',
      petAge: 'Adult',
      petGender: 'Female',
      petSize: 'Small',
    ),

    PetDetailDataModel(
      petName: 'Cutie',
      petImage: 'assets/image/cutie_chinchillas.jpg',
      petType: 'Other',
      distanceFromPet: '3.2km',
      petBreed: 'Chinchilla',
      petOrganization: 'FurEver Friends',
      petDescription: 'Cutie is a soft, gray Chinchilla with a gentle and shy personality. Known for her dense, soft fur, she enjoys dust baths and is active in the evening.',
      petDescription2: 'Chinchillas like Cutie need a spacious cage with climbing structures and hiding spots. She\'s sensitive to heat and prefers a cool, quiet environment.',
      petOrganizationAddress: '789 Persian Alley, Orlando, FL 32801',
      petOrganizationImage: '',
      petAdoptInfo: 'Cutie would thrive in a calm home with space for her to jump and play. She\'s best suited for someone who can provide a cool, low-stress environment.',
      petAdoptInfo2: 'To adopt Cutie, contact FurEver Friends at (555) 101-2020. She\'s healthy, well-cared-for, and ready for a loving home.',
      petAge: 'Young',
      petGender: 'Female',
      petSize: 'Small',
    ),


  ];

}